apiVersion: v1
kind: Service
metadata:
  name: agentic-finance-crew
  labels:
    app: agentic-finance-crew
spec:
  type: ClusterIP
  selector:
    app: agentic-finance-crew
  ports:
    - name: http
      port: 80
      targetPort: 8000
